"""initial_schema

Revision ID: 001
Revises: 
Create Date: 2026-06-26 18:35:42.434256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('funnel_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='leads'
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'converted', 'lost', name='leadstatus', schema='leads'), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('temperature_score', sa.Integer(), nullable=True),
    sa.Column('analysis_status', sa.Enum('idle', 'pending', 'processing', 'completed', 'failed', name='analysisstatus', schema='leads'), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('analysis_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_processing', sa.Boolean(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['leads.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='leads'
    )
    op.create_index(op.f('ix_leads_leads_analysis_status'), 'leads', ['analysis_status'], unique=False, schema='leads')
    op.create_index(op.f('ix_leads_leads_phone'), 'leads', ['phone'], unique=False, schema='leads')
    op.create_index(op.f('ix_leads_leads_status'), 'leads', ['status'], unique=False, schema='leads')
    op.create_index(op.f('ix_leads_leads_tenant_id'), 'leads', ['tenant_id'], unique=False, schema='leads')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['leads.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='leads'
    )
    op.create_index(op.f('ix_leads_users_email'), 'users', ['email'], unique=True, schema='leads')
    op.create_index(op.f('ix_leads_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='leads')
    op.create_table('whatsapp_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QR_CODE_READY', 'CONNECTING', 'CONNECTED', 'DISCONNECTED', 'ERROR', name='sessionstatus', schema='leads'), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('qr_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('connected_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['leads.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='leads'
    )
    op.create_index(op.f('ix_leads_whatsapp_sessions_session_id'), 'whatsapp_sessions', ['session_id'], unique=True, schema='leads')
    op.create_index(op.f('ix_leads_whatsapp_sessions_tenant_id'), 'whatsapp_sessions', ['tenant_id'], unique=False, schema='leads')
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('temperature_score', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=False),
    sa.Column('qualitative_tips', sa.Text(), nullable=False),
    sa.Column('suggested_reply', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='leads'
    )
    op.create_index(op.f('ix_leads_analyses_lead_id'), 'analyses', ['lead_id'], unique=False, schema='leads')
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='messagedirection', schema='leads'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='leads'
    )
    op.create_index(op.f('ix_leads_messages_lead_id'), 'messages', ['lead_id'], unique=False, schema='leads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_messages_lead_id'), table_name='messages', schema='leads')
    op.drop_table('messages', schema='leads')
    op.drop_index(op.f('ix_leads_analyses_lead_id'), table_name='analyses', schema='leads')
    op.drop_table('analyses', schema='leads')
    op.drop_index(op.f('ix_leads_whatsapp_sessions_tenant_id'), table_name='whatsapp_sessions', schema='leads')
    op.drop_index(op.f('ix_leads_whatsapp_sessions_session_id'), table_name='whatsapp_sessions', schema='leads')
    op.drop_table('whatsapp_sessions', schema='leads')
    op.drop_index(op.f('ix_leads_users_tenant_id'), table_name='users', schema='leads')
    op.drop_index(op.f('ix_leads_users_email'), table_name='users', schema='leads')
    op.drop_table('users', schema='leads')
    op.drop_index(op.f('ix_leads_leads_tenant_id'), table_name='leads', schema='leads')
    op.drop_index(op.f('ix_leads_leads_status'), table_name='leads', schema='leads')
    op.drop_index(op.f('ix_leads_leads_phone'), table_name='leads', schema='leads')
    op.drop_index(op.f('ix_leads_leads_analysis_status'), table_name='leads', schema='leads')
    op.drop_table('leads', schema='leads')
    op.drop_table('tenants', schema='leads')
    # ### end Alembic commands ###
